# Generated by Django 5.1.7 on 2025-04-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_instruction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instruction",
            name="image",
        ),
    ]
