# Generated by Django 5.1.7 on 2025-11-08 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_instruction_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Assign a user to provide them with a custom home page. Leave blank for the default home page.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_page",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
